// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: base.proto
// Protobuf C++ Version: 6.33.0-dev

#include "base.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;

namespace base {
    inline constexpr Person_PhoneNumber::Impl_::Impl_(
        ::_pbi::ConstantInitialized) noexcept
        : _cached_size_{0},
          number_(
              &::google::protobuf::internal::fixed_address_empty_string,
              ::_pbi::ConstantInitialized()),
          type_{static_cast<::base::Person_PhoneType>(0)} {
    }

    template<typename>
    PROTOBUF_CONSTEXPR Person_PhoneNumber::Person_PhoneNumber(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message (Person_PhoneNumber_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
        : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
          _impl_(::_pbi::ConstantInitialized()) {
    }

    struct Person_PhoneNumberDefaultTypeInternal {
        PROTOBUF_CONSTEXPR Person_PhoneNumberDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {
        }

        ~Person_PhoneNumberDefaultTypeInternal() {
        }

        union {
            Person_PhoneNumber _instance;
        };
    };

    PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 Person_PhoneNumberDefaultTypeInternal _Person_PhoneNumber_default_instance_;

    inline constexpr Person::Impl_::Impl_(
        ::_pbi::ConstantInitialized) noexcept
        : _cached_size_{0},
          phones_{},
          name_(
              &::google::protobuf::internal::fixed_address_empty_string,
              ::_pbi::ConstantInitialized()),
          email_(
              &::google::protobuf::internal::fixed_address_empty_string,
              ::_pbi::ConstantInitialized()),
          id_{0} {
    }

    template<typename>
    PROTOBUF_CONSTEXPR Person::Person(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message (Person_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
        : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
          _impl_(::_pbi::ConstantInitialized()) {
    }

    struct PersonDefaultTypeInternal {
        PROTOBUF_CONSTEXPR PersonDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {
        }

        ~PersonDefaultTypeInternal() {
        }

        union {
            Person _instance;
        };
    };

    PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PersonDefaultTypeInternal _Person_default_instance_;

    inline constexpr AddressBook::Impl_::Impl_(
        ::_pbi::ConstantInitialized) noexcept
        : _cached_size_{0},
          people_{} {
    }

    template<typename>
    PROTOBUF_CONSTEXPR AddressBook::AddressBook(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message (AddressBook_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
        : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
          _impl_(::_pbi::ConstantInitialized()) {
    }

    struct AddressBookDefaultTypeInternal {
        PROTOBUF_CONSTEXPR AddressBookDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {
        }

        ~AddressBookDefaultTypeInternal() {
        }

        union {
            AddressBook _instance;
        };
    };

    PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 AddressBookDefaultTypeInternal _AddressBook_default_instance_;
} // namespace base
static const ::_pb::EnumDescriptor *PROTOBUF_NONNULL
file_level_enum_descriptors_base_2eproto [1];
static constexpr const ::_pb::ServiceDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
file_level_service_descriptors_base_2eproto=
nullptr;
const ::uint32_t
        TableStruct_base_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
            protodesc_cold) =
 {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::base::Person_PhoneNumber, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::base::Person_PhoneNumber, _impl_.number_),
        PROTOBUF_FIELD_OFFSET(::base::Person_PhoneNumber, _impl_.type_),
        0,
        1,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::base::Person, _impl_._has_bits_),
        7, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::base::Person, _impl_.name_),
        PROTOBUF_FIELD_OFFSET(::base::Person, _impl_.id_),
        PROTOBUF_FIELD_OFFSET(::base::Person, _impl_.email_),
        PROTOBUF_FIELD_OFFSET(::base::Person, _impl_.phones_),
        1,
        3,
        2,
        0,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::base::AddressBook, _impl_._has_bits_),
        4, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::base::AddressBook, _impl_.people_),
        0,
};

static const ::_pbi::MigrationSchema
        schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) =
 {
        {0, sizeof(::base::Person_PhoneNumber)},
        {7, sizeof(::base::Person)},
        {18, sizeof(::base::AddressBook)},
};
static const ::_pb::Message *PROTOBUF_NONNULL
const file_default_instances [] = {
    &::base::_Person_PhoneNumber_default_instance_._instance,
    &::base::_Person_default_instance_._instance,
    &::base::_AddressBook_default_instance_._instance,
};
const char descriptor_table_protodef_base_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
            protodesc_cold) =
 {
    "\n\nbase.proto\022\004base\"\315\001\n\006Person\022\014\n\004name\030\001 "
    "\001(\t\022\n\n\002id\030\002 \001(\005\022\r\n\005email\030\003 \001(\t\022(\n\006phones"
    "\030\004 \003(\0132\030.base.Person.PhoneNumber\032C\n\013Phon"
    "eNumber\022\016\n\006number\030\001 \001(\t\022$\n\004type\030\002 \001(\0162\026."
    "base.Person.PhoneType\"+\n\tPhoneType\022\n\n\006MO"
    "BILE\020\000\022\010\n\004HOME\020\001\022\010\n\004WORK\020\002\"+\n\013AddressBoo"
    "k\022\034\n\006people\030\001 \003(\0132\014.base.Personb\006proto3"
};
static ::absl::once_flag descriptor_table_base_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_base_2eproto = {
    false,
    false,
    279,
    descriptor_table_protodef_base_2eproto,
    "base.proto",
    &descriptor_table_base_2eproto_once,
    nullptr,
    0,
    3,
    schemas,
    file_default_instances,
    TableStruct_base_2eproto::offsets,
    file_level_enum_descriptors_base_2eproto,
    file_level_service_descriptors_base_2eproto,
};

namespace base {
    const ::google::protobuf::EnumDescriptor * PROTOBUF_NONNULL Person_PhoneType_descriptor() {
        ::google::protobuf::internal::AssignDescriptors(&descriptor_table_base_2eproto);
        return file_level_enum_descriptors_base_2eproto[0];
    }

PROTOBUF_CONSTINIT const uint32_t Person_PhoneType_internal_data_[] = {
        196608u, 0u,
    };
    // ===================================================================

    class Person_PhoneNumber::_Internal {
    public:
        using HasBits =
        decltype(::std::declval<Person_PhoneNumber>()._impl_._has_bits_);
        static constexpr ::int32_t kHasBitsOffset =
                8 * PROTOBUF_FIELD_OFFSET(Person_PhoneNumber, _impl_._has_bits_);
    };

    Person_PhoneNumber::Person_PhoneNumber(::google::protobuf::Arena * PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Person_PhoneNumber_class_data_.base()) {

#else   // PROTOBUF_CUSTOM_VTABLE
        : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
        SharedCtor(arena);
        // @@protoc_insertion_point(arena_constructor:base.Person.PhoneNumber)
    }

    PROTOBUF_NDEBUG_INLINE Person_PhoneNumber::Impl_::Impl_(
        [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
        [[maybe_unused]] ::google::protobuf::Arena * PROTOBUF_NULLABLE arena, const Impl_ &from,
        [[maybe_unused]] const ::base::Person_PhoneNumber &from_msg)
        : _has_bits_{from._has_bits_},
          _cached_size_{0},
          number_(arena, from.number_) {
    }

    Person_PhoneNumber::Person_PhoneNumber(
        ::google::protobuf::Arena * PROTOBUF_NULLABLE arena,
    
    const Person_PhoneNumber &from
    )
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Person_PhoneNumber_class_data_.base()) {

#else   // PROTOBUF_CUSTOM_VTABLE
    :
    ::google::protobuf::Message (arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
        Person_PhoneNumber *const _this = this;
        (void) _this;
        _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
            from._internal_metadata_);
        new(&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
        _impl_.type_ = from._impl_.type_;

        // @@protoc_insertion_point(copy_constructor:base.Person.PhoneNumber)
    }

    PROTOBUF_NDEBUG_INLINE Person_PhoneNumber::Impl_::Impl_(
        [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
        [[maybe_unused]] ::google::protobuf::Arena * PROTOBUF_NULLABLE arena)
        : _cached_size_{0},
          number_(arena) {
    }

    inline void Person_PhoneNumber::SharedCtor(::_pb::Arena * PROTOBUF_NULLABLE arena) {
        new(&_impl_) Impl_(internal_visibility(), arena);
        _impl_.type_ = {};
    }

    Person_PhoneNumber::~Person_PhoneNumber() {
        // @@protoc_insertion_point(destructor:base.Person.PhoneNumber)
        SharedDtor(*this);
    }

    inline void Person_PhoneNumber::SharedDtor(MessageLite &self) {
        Person_PhoneNumber &this_ = static_cast<Person_PhoneNumber &>(self);
        if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
            this_.CheckHasBitConsistency();
        }
        this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
        ABSL_DCHECK(this_.GetArena() == nullptr);
        this_._impl_.number_.Destroy();
        this_._impl_.~Impl_();
    }

    inline void * PROTOBUF_NONNULL Person_PhoneNumber::PlacementNew_(
        const void *PROTOBUF_NONNULL, void * PROTOBUF_NONNULL mem,
        ::google::protobuf::Arena * PROTOBUF_NULLABLE arena) {
        return ::new(mem) Person_PhoneNumber(arena);
    }

    constexpr auto Person_PhoneNumber::InternalNewImpl_() {
        return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(Person_PhoneNumber),
                                                                      alignof(Person_PhoneNumber));
    }

    constexpr auto Person_PhoneNumber::InternalGenerateClassData_() {
        return ::google::protobuf::internal::ClassDataFull{
            ::google::protobuf::internal::ClassData{
                &_Person_PhoneNumber_default_instance_._instance,
                &_table_.header,
                nullptr, // OnDemandRegisterArenaDtor
                nullptr, // IsInitialized
                &Person_PhoneNumber::MergeImpl,
                ::google::protobuf::Message::GetNewImpl<Person_PhoneNumber>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
                &Person_PhoneNumber::SharedDtor,
                        ::google::protobuf::Message::GetClearImpl<Person_PhoneNumber>(), &
                        Person_PhoneNumber::ByteSizeLong,
                        &Person_PhoneNumber::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
                PROTOBUF_FIELD_OFFSET(Person_PhoneNumber, _impl_._cached_size_),
                false,
            },
            &Person_PhoneNumber::kDescriptorMethods,
            &descriptor_table_base_2eproto,
            nullptr, // tracker
        };
    }

    PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
    const
    ::google::protobuf::internal::ClassDataFull Person_PhoneNumber_class_data_ =
            Person_PhoneNumber::InternalGenerateClassData_();

    PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData *PROTOBUF_NONNULL

    Person_PhoneNumber::GetClassData() const {
        ::google::protobuf::internal::PrefetchToLocalCache(&Person_PhoneNumber_class_data_);
        ::google::protobuf::internal::PrefetchToLocalCache(Person_PhoneNumber_class_data_.tc_table);
        return Person_PhoneNumber_class_data_.base();
    }

    PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
    const ::_pbi::TcParseTable<1, 2, 0, 38, 2>
    Person_PhoneNumber::_table_ = {
        {
            PROTOBUF_FIELD_OFFSET(Person_PhoneNumber, _impl_._has_bits_),
            0, // no _extensions_
            2, 8, // max_field_number, fast_idx_mask
            offsetof(decltype(_table_), field_lookup_table),
            4294967292, // skipmap
            offsetof(decltype(_table_), field_entries),
            2, // num_field_entries
            0, // num_aux_entries
            offsetof(decltype(_table_), field_names), // no aux_entries
            Person_PhoneNumber_class_data_.base(),
            nullptr, // post_loop_handler
            ::_pbi::TcParser::GenericFallback, // fallback
#ifdef PROTOBUF_PREFETCH_PARSE_TABLE
            ::_pbi::TcParser::GetTable<::base::Person_PhoneNumber>(), // to_prefetch
#endif  // PROTOBUF_PREFETCH_PARSE_TABLE
        },
        {
            {
                // .base.Person.PhoneType type = 2;
                {
                    ::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Person_PhoneNumber, _impl_.type_), 1>(),
                    {16, 1, 0, PROTOBUF_FIELD_OFFSET(Person_PhoneNumber, _impl_.type_)}
                },
                // string number = 1;
                {
                    ::_pbi::TcParser::FastUS1,
                    {10, 0, 0, PROTOBUF_FIELD_OFFSET(Person_PhoneNumber, _impl_.number_)}
                },
            }
        },
        {
            {
                65535, 65535
            }
        },
        {
            {
                // string number = 1;
                {
                    PROTOBUF_FIELD_OFFSET(Person_PhoneNumber, _impl_.number_), _Internal::kHasBitsOffset + 0, 0,
                    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)
                },
                // .base.Person.PhoneType type = 2;
                {
                    PROTOBUF_FIELD_OFFSET(Person_PhoneNumber, _impl_.type_), _Internal::kHasBitsOffset + 1, 0,
                    (0 | ::_fl::kFcOptional | ::_fl::kOpenEnum)
                },
            }
        },
        // no aux_entries
        {
            {
                "\27\6\0\0\0\0\0\0"
                "base.Person.PhoneNumber"
                "number"
            }
        },
    };

PROTOBUF_NOINLINE void Person_PhoneNumber::Clear() {
        // @@protoc_insertion_point(message_clear_start:base.Person.PhoneNumber)
        ::google::protobuf::internal::TSanWrite(&_impl_);
        ::uint32_t cached_has_bits = 0;
        // Prevent compiler warnings about cached_has_bits being unused
        (void) cached_has_bits;

        cached_has_bits = _impl_._has_bits_[0];
        if (CheckHasBit(cached_has_bits, 0x00000001U)) {
            _impl_.number_.ClearNonDefaultToEmpty();
        }
        _impl_.type_ = 0;
        _impl_._has_bits_.Clear();
        _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
    }

#if defined(PROTOBUF_CUSTOM_VTABLE)
    ::uint8_t * PROTOBUF_NONNULL Person_PhoneNumber::_InternalSerialize(
        const ::google::protobuf::MessageLite &base, ::uint8_t * PROTOBUF_NONNULL target,
        ::google::protobuf::io::EpsCopyOutputStream * PROTOBUF_NONNULL stream) {
        const Person_PhoneNumber &this_ = static_cast<const Person_PhoneNumber &>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
    ::uint8_t * PROTOBUF_NONNULL Person_PhoneNumber::_InternalSerialize(
        ::uint8_t * PROTOBUF_NONNULL target,
        ::google::protobuf::io::EpsCopyOutputStream * PROTOBUF_NONNULL stream)
    const
 {
  const Person_PhoneNumber& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:base.Person.PhoneNumber)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // string number = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_number().empty()) {
      const ::std::string& _s = this_._internal_number();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "base.Person.PhoneNumber.number");
      target = stream->WriteStringMaybeAliased(1, _s, target);
    }
  }

  // .base.Person.PhoneType type = 2;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (this_._internal_type() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteEnumToArray(
          2, this_._internal_type(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:base.Person.PhoneNumber)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
    ::size_t Person_PhoneNumber::ByteSizeLong(const MessageLite &base) {
        const Person_PhoneNumber &this_ = static_cast<const Person_PhoneNumber &>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
    ::size_t Person_PhoneNumber::ByteSizeLong() const {
        const Person_PhoneNumber &this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
        // @@protoc_insertion_point(message_byte_size_start:base.Person.PhoneNumber)
        ::size_t total_size = 0;

        ::uint32_t cached_has_bits = 0;
        // Prevent compiler warnings about cached_has_bits being unused
        (void) cached_has_bits;

        ::_pbi::Prefetch5LinesFrom7Lines(&this_);
        cached_has_bits = this_._impl_._has_bits_[0];
        if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
            // string number = 1;
            if (CheckHasBit(cached_has_bits, 0x00000001U)) {
                if (!this_._internal_number().empty()) {
                    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                        this_._internal_number());
                }
            }
            // .base.Person.PhoneType type = 2;
            if (CheckHasBit(cached_has_bits, 0x00000002U)) {
                if (this_._internal_type() != 0) {
                    total_size += 1 +
                            ::_pbi::WireFormatLite::EnumSize(this_._internal_type());
                }
            }
        }
        return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                   &this_._impl_._cached_size_);
    }

    void Person_PhoneNumber::MergeImpl(::google::protobuf::MessageLite &to_msg,
                                       const ::google::protobuf::MessageLite &from_msg) {
        auto *const _this =
                static_cast<Person_PhoneNumber *>(&to_msg);
        auto &from = static_cast<const Person_PhoneNumber &>(from_msg);
        if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
            from.CheckHasBitConsistency();
        }
        // @@protoc_insertion_point(class_specific_merge_from_start:base.Person.PhoneNumber)
        ABSL_DCHECK_NE(&from, _this);
        ::uint32_t cached_has_bits = 0;
        (void) cached_has_bits;

        cached_has_bits = from._impl_._has_bits_[0];
        if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
            if (CheckHasBit(cached_has_bits, 0x00000001U)) {
                if (!from._internal_number().empty()) {
                    _this->_internal_set_number(from._internal_number());
                } else {
                    if (_this->_impl_.number_.IsDefault()) {
                        _this->_internal_set_number("");
                    }
                }
            }
            if (CheckHasBit(cached_has_bits, 0x00000002U)) {
                if (from._internal_type() != 0) {
                    _this->_impl_.type_ = from._impl_.type_;
                }
            }
        }
        _this->_impl_._has_bits_[0] |= cached_has_bits;
        _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
            from._internal_metadata_);
    }

    void Person_PhoneNumber::CopyFrom(const Person_PhoneNumber &from) {
        // @@protoc_insertion_point(class_specific_copy_from_start:base.Person.PhoneNumber)
        if (&from == this) return;
        Clear();
        MergeFrom(from);
    }


    void Person_PhoneNumber::InternalSwap(Person_PhoneNumber * PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
        using ::std::swap;
        auto *arena = GetArena();
        ABSL_DCHECK_EQ(arena, other->GetArena());
        _internal_metadata_.InternalSwap(&other->_internal_metadata_);
        swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
        ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.number_, &other->_impl_.number_, arena);
        swap(_impl_.type_, other->_impl_.type_);
    }

    ::google::protobuf::Metadata Person_PhoneNumber::GetMetadata() const {
        return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
    }

    // ===================================================================

    class Person::_Internal {
    public:
        using HasBits =
        decltype(::std::declval<Person>()._impl_._has_bits_);
        static constexpr ::int32_t kHasBitsOffset =
                8 * PROTOBUF_FIELD_OFFSET(Person, _impl_._has_bits_);
    };

    Person::Person(::google::protobuf::Arena * PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Person_class_data_.base()) {

#else   // PROTOBUF_CUSTOM_VTABLE
        : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
        SharedCtor(arena);
        // @@protoc_insertion_point(arena_constructor:base.Person)
    }

    PROTOBUF_NDEBUG_INLINE Person::Impl_::Impl_(
        [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
        [[maybe_unused]] ::google::protobuf::Arena * PROTOBUF_NULLABLE arena, const Impl_ &from,
        [[maybe_unused]] const ::base::Person &from_msg)
        : _has_bits_{from._has_bits_},
          _cached_size_{0},
          phones_{visibility, arena, from.phones_},
          name_(arena, from.name_),
          email_(arena, from.email_) {
    }

    Person::Person(
        ::google::protobuf::Arena * PROTOBUF_NULLABLE arena,
    
    const Person &from
    )
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Person_class_data_.base()) {

#else   // PROTOBUF_CUSTOM_VTABLE
    :
    ::google::protobuf::Message (arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
        Person *const _this = this;
        (void) _this;
        _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
            from._internal_metadata_);
        new(&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
        _impl_.id_ = from._impl_.id_;

        // @@protoc_insertion_point(copy_constructor:base.Person)
    }

    PROTOBUF_NDEBUG_INLINE Person::Impl_::Impl_(
        [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
        [[maybe_unused]] ::google::protobuf::Arena * PROTOBUF_NULLABLE arena)
        : _cached_size_{0},
          phones_{visibility, arena},
          name_(arena),
          email_(arena) {
    }

    inline void Person::SharedCtor(::_pb::Arena * PROTOBUF_NULLABLE arena) {
        new(&_impl_) Impl_(internal_visibility(), arena);
        _impl_.id_ = {};
    }

    Person::~Person() {
        // @@protoc_insertion_point(destructor:base.Person)
        SharedDtor(*this);
    }

    inline void Person::SharedDtor(MessageLite &self) {
        Person &this_ = static_cast<Person &>(self);
        if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
            this_.CheckHasBitConsistency();
        }
        this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
        ABSL_DCHECK(this_.GetArena() == nullptr);
        this_._impl_.name_.Destroy();
        this_._impl_.email_.Destroy();
        this_._impl_.~Impl_();
    }

    inline void * PROTOBUF_NONNULL Person::PlacementNew_(
        const void *PROTOBUF_NONNULL, void * PROTOBUF_NONNULL mem,
        ::google::protobuf::Arena * PROTOBUF_NULLABLE arena) {
        return ::new(mem) Person(arena);
    }

    constexpr auto Person::InternalNewImpl_() {
        constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
            PROTOBUF_FIELD_OFFSET(Person, _impl_.phones_) +
            decltype(Person::_impl_.phones_)::
            InternalGetArenaOffset(
                ::google::protobuf::Message::internal_visibility()),
        });
        if (arena_bits.has_value()) {
            return ::google::protobuf::internal::MessageCreator::CopyInit(
                sizeof(Person), alignof(Person), *arena_bits);
        } else {
            return ::google::protobuf::internal::MessageCreator(&Person::PlacementNew_,
                                                                sizeof(Person),
                                                                alignof(Person));
        }
    }

    constexpr auto Person::InternalGenerateClassData_() {
        return ::google::protobuf::internal::ClassDataFull{
            ::google::protobuf::internal::ClassData{
                &_Person_default_instance_._instance,
                &_table_.header,
                nullptr, // OnDemandRegisterArenaDtor
                nullptr, // IsInitialized
                &Person::MergeImpl,
                ::google::protobuf::Message::GetNewImpl<Person>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
                &Person::SharedDtor,
                        ::google::protobuf::Message::GetClearImpl<Person>(), &Person::ByteSizeLong,
                        &Person::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
                PROTOBUF_FIELD_OFFSET(Person, _impl_._cached_size_),
                false,
            },
            &Person::kDescriptorMethods,
            &descriptor_table_base_2eproto,
            nullptr, // tracker
        };
    }

    PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
    const
    ::google::protobuf::internal::ClassDataFull Person_class_data_ =
            Person::InternalGenerateClassData_();

    PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData *PROTOBUF_NONNULL

    Person::GetClassData() const {
        ::google::protobuf::internal::PrefetchToLocalCache(&Person_class_data_);
        ::google::protobuf::internal::PrefetchToLocalCache(Person_class_data_.tc_table);
        return Person_class_data_.base();
    }

    PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
    const ::_pbi::TcParseTable<2, 4, 1, 29, 2>
    Person::_table_ = {
        {
            PROTOBUF_FIELD_OFFSET(Person, _impl_._has_bits_),
            0, // no _extensions_
            4, 24, // max_field_number, fast_idx_mask
            offsetof(decltype(_table_), field_lookup_table),
            4294967280, // skipmap
            offsetof(decltype(_table_), field_entries),
            4, // num_field_entries
            1, // num_aux_entries
            offsetof(decltype(_table_), aux_entries),
            Person_class_data_.base(),
            nullptr, // post_loop_handler
            ::_pbi::TcParser::GenericFallback, // fallback
#ifdef PROTOBUF_PREFETCH_PARSE_TABLE
            ::_pbi::TcParser::GetTable<::base::Person>(), // to_prefetch
#endif  // PROTOBUF_PREFETCH_PARSE_TABLE
        },
        {
            {
                // repeated .base.Person.PhoneNumber phones = 4;
                {
                    ::_pbi::TcParser::FastMtR1,
                    {34, 0, 0, PROTOBUF_FIELD_OFFSET(Person, _impl_.phones_)}
                },
                // string name = 1;
                {
                    ::_pbi::TcParser::FastUS1,
                    {10, 1, 0, PROTOBUF_FIELD_OFFSET(Person, _impl_.name_)}
                },
                // int32 id = 2;
                {
                    ::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Person, _impl_.id_), 3>(),
                    {16, 3, 0, PROTOBUF_FIELD_OFFSET(Person, _impl_.id_)}
                },
                // string email = 3;
                {
                    ::_pbi::TcParser::FastUS1,
                    {26, 2, 0, PROTOBUF_FIELD_OFFSET(Person, _impl_.email_)}
                },
            }
        },
        {
            {
                65535, 65535
            }
        },
        {
            {
                // string name = 1;
                {
                    PROTOBUF_FIELD_OFFSET(Person, _impl_.name_), _Internal::kHasBitsOffset + 1, 0,
                    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)
                },
                // int32 id = 2;
                {
                    PROTOBUF_FIELD_OFFSET(Person, _impl_.id_), _Internal::kHasBitsOffset + 3, 0,
                    (0 | ::_fl::kFcOptional | ::_fl::kInt32)
                },
                // string email = 3;
                {
                    PROTOBUF_FIELD_OFFSET(Person, _impl_.email_), _Internal::kHasBitsOffset + 2, 0,
                    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)
                },
                // repeated .base.Person.PhoneNumber phones = 4;
                {
                    PROTOBUF_FIELD_OFFSET(Person, _impl_.phones_), _Internal::kHasBitsOffset + 0, 0,
                    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)
                },
            }
        },
        {
            {
                {::_pbi::TcParser::GetTable<::base::Person_PhoneNumber>()},
            }
        },
        {
            {
                "\13\4\0\5\0\0\0\0"
                "base.Person"
                "name"
                "email"
            }
        },
    };

PROTOBUF_NOINLINE void Person::Clear() {
        // @@protoc_insertion_point(message_clear_start:base.Person)
        ::google::protobuf::internal::TSanWrite(&_impl_);
        ::uint32_t cached_has_bits = 0;
        // Prevent compiler warnings about cached_has_bits being unused
        (void) cached_has_bits;

        cached_has_bits = _impl_._has_bits_[0];
        if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
            if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
                _impl_.phones_.Clear();
            }
            if (CheckHasBit(cached_has_bits, 0x00000002U)) {
                _impl_.name_.ClearNonDefaultToEmpty();
            }
            if (CheckHasBit(cached_has_bits, 0x00000004U)) {
                _impl_.email_.ClearNonDefaultToEmpty();
            }
        }
        _impl_.id_ = 0;
        _impl_._has_bits_.Clear();
        _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
    }

#if defined(PROTOBUF_CUSTOM_VTABLE)
    ::uint8_t * PROTOBUF_NONNULL Person::_InternalSerialize(
        const ::google::protobuf::MessageLite &base, ::uint8_t * PROTOBUF_NONNULL target,
        ::google::protobuf::io::EpsCopyOutputStream * PROTOBUF_NONNULL stream) {
        const Person &this_ = static_cast<const Person &>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
    ::uint8_t * PROTOBUF_NONNULL Person::_InternalSerialize(
        ::uint8_t * PROTOBUF_NONNULL target,
        ::google::protobuf::io::EpsCopyOutputStream * PROTOBUF_NONNULL stream)
    const
 {
  const Person& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:base.Person)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // string name = 1;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (!this_._internal_name().empty()) {
      const ::std::string& _s = this_._internal_name();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "base.Person.name");
      target = stream->WriteStringMaybeAliased(1, _s, target);
    }
  }

  // int32 id = 2;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    if (this_._internal_id() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<2>(
              stream, this_._internal_id(), target);
    }
  }

  // string email = 3;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    if (!this_._internal_email().empty()) {
      const ::std::string& _s = this_._internal_email();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "base.Person.email");
      target = stream->WriteStringMaybeAliased(3, _s, target);
    }
  }

  // repeated .base.Person.PhoneNumber phones = 4;
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
    for (unsigned i = 0, n = static_cast<unsigned>(
                             this_._internal_phones_size());
         i < n; i++) {
      const auto& repfield = this_._internal_phones().Get(i);
      target =
          ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
              4, repfield, repfield.GetCachedSize(),
              target, stream);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:base.Person)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
    ::size_t Person::ByteSizeLong(const MessageLite &base) {
        const Person &this_ = static_cast<const Person &>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
    ::size_t Person::ByteSizeLong() const {
        const Person &this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
        // @@protoc_insertion_point(message_byte_size_start:base.Person)
        ::size_t total_size = 0;

        ::uint32_t cached_has_bits = 0;
        // Prevent compiler warnings about cached_has_bits being unused
        (void) cached_has_bits;

        ::_pbi::Prefetch5LinesFrom7Lines(&this_);
        cached_has_bits = this_._impl_._has_bits_[0];
        if (BatchCheckHasBit(cached_has_bits, 0x0000000fU)) {
            // repeated .base.Person.PhoneNumber phones = 4;
            if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
                total_size += 1UL * this_._internal_phones_size();
                for (const auto &msg: this_._internal_phones()) {
                    total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
                }
            }
            // string name = 1;
            if (CheckHasBit(cached_has_bits, 0x00000002U)) {
                if (!this_._internal_name().empty()) {
                    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                        this_._internal_name());
                }
            }
            // string email = 3;
            if (CheckHasBit(cached_has_bits, 0x00000004U)) {
                if (!this_._internal_email().empty()) {
                    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                        this_._internal_email());
                }
            }
            // int32 id = 2;
            if (CheckHasBit(cached_has_bits, 0x00000008U)) {
                if (this_._internal_id() != 0) {
                    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                        this_._internal_id());
                }
            }
        }
        return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                   &this_._impl_._cached_size_);
    }

    void Person::MergeImpl(::google::protobuf::MessageLite &to_msg,
                           const ::google::protobuf::MessageLite &from_msg) {
        auto *const _this =
                static_cast<Person *>(&to_msg);
        auto &from = static_cast<const Person &>(from_msg);
        if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
            from.CheckHasBitConsistency();
        }
        // @@protoc_insertion_point(class_specific_merge_from_start:base.Person)
        ABSL_DCHECK_NE(&from, _this);
        ::uint32_t cached_has_bits = 0;
        (void) cached_has_bits;

        cached_has_bits = from._impl_._has_bits_[0];
        if (BatchCheckHasBit(cached_has_bits, 0x0000000fU)) {
            if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
                _this->_internal_mutable_phones()->MergeFrom(
                    from._internal_phones());
            }
            if (CheckHasBit(cached_has_bits, 0x00000002U)) {
                if (!from._internal_name().empty()) {
                    _this->_internal_set_name(from._internal_name());
                } else {
                    if (_this->_impl_.name_.IsDefault()) {
                        _this->_internal_set_name("");
                    }
                }
            }
            if (CheckHasBit(cached_has_bits, 0x00000004U)) {
                if (!from._internal_email().empty()) {
                    _this->_internal_set_email(from._internal_email());
                } else {
                    if (_this->_impl_.email_.IsDefault()) {
                        _this->_internal_set_email("");
                    }
                }
            }
            if (CheckHasBit(cached_has_bits, 0x00000008U)) {
                if (from._internal_id() != 0) {
                    _this->_impl_.id_ = from._impl_.id_;
                }
            }
        }
        _this->_impl_._has_bits_[0] |= cached_has_bits;
        _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
            from._internal_metadata_);
    }

    void Person::CopyFrom(const Person &from) {
        // @@protoc_insertion_point(class_specific_copy_from_start:base.Person)
        if (&from == this) return;
        Clear();
        MergeFrom(from);
    }


    void Person::InternalSwap(Person * PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
        using ::std::swap;
        auto *arena = GetArena();
        ABSL_DCHECK_EQ(arena, other->GetArena());
        _internal_metadata_.InternalSwap(&other->_internal_metadata_);
        swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
        _impl_.phones_.InternalSwap(&other->_impl_.phones_);
        ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.name_, &other->_impl_.name_, arena);
        ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.email_, &other->_impl_.email_, arena);
        swap(_impl_.id_, other->_impl_.id_);
    }

    ::google::protobuf::Metadata Person::GetMetadata() const {
        return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
    }

    // ===================================================================

    class AddressBook::_Internal {
    public:
        using HasBits =
        decltype(::std::declval<AddressBook>()._impl_._has_bits_);
        static constexpr ::int32_t kHasBitsOffset =
                8 * PROTOBUF_FIELD_OFFSET(AddressBook, _impl_._has_bits_);
    };

    AddressBook::AddressBook(::google::protobuf::Arena * PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, AddressBook_class_data_.base()) {

#else   // PROTOBUF_CUSTOM_VTABLE
        : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
        SharedCtor(arena);
        // @@protoc_insertion_point(arena_constructor:base.AddressBook)
    }

    PROTOBUF_NDEBUG_INLINE AddressBook::Impl_::Impl_(
        [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
        [[maybe_unused]] ::google::protobuf::Arena * PROTOBUF_NULLABLE arena, const Impl_ &from,
        [[maybe_unused]] const ::base::AddressBook &from_msg)
        : _has_bits_{from._has_bits_},
          _cached_size_{0},
          people_{visibility, arena, from.people_} {
    }

    AddressBook::AddressBook(
        ::google::protobuf::Arena * PROTOBUF_NULLABLE arena,
    
    const AddressBook &from
    )
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, AddressBook_class_data_.base()) {

#else   // PROTOBUF_CUSTOM_VTABLE
    :
    ::google::protobuf::Message (arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
        AddressBook *const _this = this;
        (void) _this;
        _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
            from._internal_metadata_);
        new(&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

        // @@protoc_insertion_point(copy_constructor:base.AddressBook)
    }

    PROTOBUF_NDEBUG_INLINE AddressBook::Impl_::Impl_(
        [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
        [[maybe_unused]] ::google::protobuf::Arena * PROTOBUF_NULLABLE arena)
        : _cached_size_{0},
          people_{visibility, arena} {
    }

    inline void AddressBook::SharedCtor(::_pb::Arena * PROTOBUF_NULLABLE arena) {
        new(&_impl_) Impl_(internal_visibility(), arena);
    }

    AddressBook::~AddressBook() {
        // @@protoc_insertion_point(destructor:base.AddressBook)
        SharedDtor(*this);
    }

    inline void AddressBook::SharedDtor(MessageLite &self) {
        AddressBook &this_ = static_cast<AddressBook &>(self);
        if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
            this_.CheckHasBitConsistency();
        }
        this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
        ABSL_DCHECK(this_.GetArena() == nullptr);
        this_._impl_.~Impl_();
    }

    inline void * PROTOBUF_NONNULL AddressBook::PlacementNew_(
        const void *PROTOBUF_NONNULL, void * PROTOBUF_NONNULL mem,
        ::google::protobuf::Arena * PROTOBUF_NULLABLE arena) {
        return ::new(mem) AddressBook(arena);
    }

    constexpr auto AddressBook::InternalNewImpl_() {
        constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
            PROTOBUF_FIELD_OFFSET(AddressBook, _impl_.people_) +
            decltype(AddressBook::_impl_.people_)::
            InternalGetArenaOffset(
                ::google::protobuf::Message::internal_visibility()),
        });
        if (arena_bits.has_value()) {
            return ::google::protobuf::internal::MessageCreator::ZeroInit(
                sizeof(AddressBook), alignof(AddressBook), *arena_bits);
        } else {
            return ::google::protobuf::internal::MessageCreator(&AddressBook::PlacementNew_,
                                                                sizeof(AddressBook),
                                                                alignof(AddressBook));
        }
    }

    constexpr auto AddressBook::InternalGenerateClassData_() {
        return ::google::protobuf::internal::ClassDataFull{
            ::google::protobuf::internal::ClassData{
                &_AddressBook_default_instance_._instance,
                &_table_.header,
                nullptr, // OnDemandRegisterArenaDtor
                nullptr, // IsInitialized
                &AddressBook::MergeImpl,
                ::google::protobuf::Message::GetNewImpl<AddressBook>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
                &AddressBook::SharedDtor,
                        ::google::protobuf::Message::GetClearImpl<AddressBook>(), &AddressBook::ByteSizeLong,
                        &AddressBook::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
                PROTOBUF_FIELD_OFFSET(AddressBook, _impl_._cached_size_),
                false,
            },
            &AddressBook::kDescriptorMethods,
            &descriptor_table_base_2eproto,
            nullptr, // tracker
        };
    }

    PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
    const
    ::google::protobuf::internal::ClassDataFull AddressBook_class_data_ =
            AddressBook::InternalGenerateClassData_();

    PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData *PROTOBUF_NONNULL

    AddressBook::GetClassData() const {
        ::google::protobuf::internal::PrefetchToLocalCache(&AddressBook_class_data_);
        ::google::protobuf::internal::PrefetchToLocalCache(AddressBook_class_data_.tc_table);
        return AddressBook_class_data_.base();
    }

    PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
    const ::_pbi::TcParseTable<0, 1, 1, 0, 2>
    AddressBook::_table_ = {
        {
            PROTOBUF_FIELD_OFFSET(AddressBook, _impl_._has_bits_),
            0, // no _extensions_
            1, 0, // max_field_number, fast_idx_mask
            offsetof(decltype(_table_), field_lookup_table),
            4294967294, // skipmap
            offsetof(decltype(_table_), field_entries),
            1, // num_field_entries
            1, // num_aux_entries
            offsetof(decltype(_table_), aux_entries),
            AddressBook_class_data_.base(),
            nullptr, // post_loop_handler
            ::_pbi::TcParser::GenericFallback, // fallback
#ifdef PROTOBUF_PREFETCH_PARSE_TABLE
            ::_pbi::TcParser::GetTable<::base::AddressBook>(), // to_prefetch
#endif  // PROTOBUF_PREFETCH_PARSE_TABLE
        },
        {
            {
                // repeated .base.Person people = 1;
                {
                    ::_pbi::TcParser::FastMtR1,
                    {10, 0, 0, PROTOBUF_FIELD_OFFSET(AddressBook, _impl_.people_)}
                },
            }
        },
        {
            {
                65535, 65535
            }
        },
        {
            {
                // repeated .base.Person people = 1;
                {
                    PROTOBUF_FIELD_OFFSET(AddressBook, _impl_.people_), _Internal::kHasBitsOffset + 0, 0,
                    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)
                },
            }
        },
        {
            {
                {::_pbi::TcParser::GetTable<::base::Person>()},
            }
        },
        {
            {
            }
        },
    };

PROTOBUF_NOINLINE void AddressBook::Clear() {
        // @@protoc_insertion_point(message_clear_start:base.AddressBook)
        ::google::protobuf::internal::TSanWrite(&_impl_);
        ::uint32_t cached_has_bits = 0;
        // Prevent compiler warnings about cached_has_bits being unused
        (void) cached_has_bits;

        cached_has_bits = _impl_._has_bits_[0];
        if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
            _impl_.people_.Clear();
        }
        _impl_._has_bits_.Clear();
        _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
    }

#if defined(PROTOBUF_CUSTOM_VTABLE)
    ::uint8_t * PROTOBUF_NONNULL AddressBook::_InternalSerialize(
        const ::google::protobuf::MessageLite &base, ::uint8_t * PROTOBUF_NONNULL target,
        ::google::protobuf::io::EpsCopyOutputStream * PROTOBUF_NONNULL stream) {
        const AddressBook &this_ = static_cast<const AddressBook &>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
    ::uint8_t * PROTOBUF_NONNULL AddressBook::_InternalSerialize(
        ::uint8_t * PROTOBUF_NONNULL target,
        ::google::protobuf::io::EpsCopyOutputStream * PROTOBUF_NONNULL stream)
    const
 {
  const AddressBook& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:base.AddressBook)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // repeated .base.Person people = 1;
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
    for (unsigned i = 0, n = static_cast<unsigned>(
                             this_._internal_people_size());
         i < n; i++) {
      const auto& repfield = this_._internal_people().Get(i);
      target =
          ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
              1, repfield, repfield.GetCachedSize(),
              target, stream);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:base.AddressBook)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
    ::size_t AddressBook::ByteSizeLong(const MessageLite &base) {
        const AddressBook &this_ = static_cast<const AddressBook &>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
    ::size_t AddressBook::ByteSizeLong() const {
        const AddressBook &this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
        // @@protoc_insertion_point(message_byte_size_start:base.AddressBook)
        ::size_t total_size = 0;

        ::uint32_t cached_has_bits = 0;
        // Prevent compiler warnings about cached_has_bits being unused
        (void) cached_has_bits;

        ::_pbi::Prefetch5LinesFrom7Lines(&this_);
        {
            // repeated .base.Person people = 1;
            cached_has_bits = this_._impl_._has_bits_[0];
            if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
                total_size += 1UL * this_._internal_people_size();
                for (const auto &msg: this_._internal_people()) {
                    total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
                }
            }
        }
        return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                   &this_._impl_._cached_size_);
    }

    void AddressBook::MergeImpl(::google::protobuf::MessageLite &to_msg,
                                const ::google::protobuf::MessageLite &from_msg) {
        auto *const _this =
                static_cast<AddressBook *>(&to_msg);
        auto &from = static_cast<const AddressBook &>(from_msg);
        if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
            from.CheckHasBitConsistency();
        }
        // @@protoc_insertion_point(class_specific_merge_from_start:base.AddressBook)
        ABSL_DCHECK_NE(&from, _this);
        ::uint32_t cached_has_bits = 0;
        (void) cached_has_bits;

        cached_has_bits = from._impl_._has_bits_[0];
        if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
            _this->_internal_mutable_people()->MergeFrom(
                from._internal_people());
        }
        _this->_impl_._has_bits_[0] |= cached_has_bits;
        _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
            from._internal_metadata_);
    }

    void AddressBook::CopyFrom(const AddressBook &from) {
        // @@protoc_insertion_point(class_specific_copy_from_start:base.AddressBook)
        if (&from == this) return;
        Clear();
        MergeFrom(from);
    }


    void AddressBook::InternalSwap(AddressBook * PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
        using ::std::swap;
        _internal_metadata_.InternalSwap(&other->_internal_metadata_);
        swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
        _impl_.people_.InternalSwap(&other->_impl_.people_);
    }

    ::google::protobuf::Metadata AddressBook::GetMetadata() const {
        return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
    }

    // @@protoc_insertion_point(namespace_scope)
} // namespace base
namespace google {
    namespace protobuf {
    } // namespace protobuf
} // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
_static_init2_ [[maybe_unused]]=
(::_pbi::AddDescriptors
(&descriptor_table_base_2eproto),
        ::std::false_type{}
);
#include "google/protobuf/port_undef.inc"